spring.application.name=pinchito

server.forward-headers-strategy=framework

github.token=${GITHUB_TOKEN:}
github.owner=${GITHUB_OWNER:ricardomaximino}
github.repo=${GITHUB_REPO:pichito-data}
github.branch=${GITHUB_BRANCH:master}
pinchito.local.storage-path=C:\\Users\\RicardoMaximinoGonca\\work\\git\\pinchito\\data\\accounts